### ISSUE TITLE
How do I use it from TypeScript or using ES5 modules import

### ISSUE THREAD

**Issue by kristianmandrup** [es-shims/Object.values#9]
Trying to import in VSC editor:

`import values from 'object.values'`

```
[ts]
Could not find a declaration file for module 'object.values'. '.../node_modules/object.values/index.js' implicitly has an 'any' type.
  Try `npm install @types/object.values` if it exists or add a new declaration (.d.ts) file containing `declare module 'object.values';`
```

Looks like I need to declare it as a module. Please add typings for TS. Thanks.

**Comment by ljharb** [comment]
No thanks, I use JavaScript, not TypeScript.

If you want a module that doesn't use TypeScript to have defined types, the proper place is to add it to the DefinitelyTyped project yourself.

**Comment by kristianmandrup** [comment]
OK, anyhow got the editor to accept it by adding the module declaration. I use it like this?

```js
import values from 'object.values'
if (!Object.values) {
  values.shim()
}
```

**Comment by ljharb** [comment]
Definitely not with the `if`; if you're going to shim, do `import shim from 'object.values/shim'; shim()` - if it's not needed, it won't do anything, but just having the method present doesn't mean that it's correct - the shim will fix it if needed.
